# Generated by Django 4.0.1 on 2022-01-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_mora_profilefeeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mora',
        ),
    ]
